[project]
name = "databricks-repo-proxy"
version = "0.0.14"
description = "A proxy for databricks repos"
readme = "README.md"
dependencies = []

[project.scripts]
db_proxy = "proxy.main:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
